version: '2'
services:
  trinket_api:
    build:
      context: .
      dockerfile: DockerFile
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "5002:5002"
    restart: always